name: CI

on: [pull_request]

jobs:
  stage-one:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: 'Install Format tools'
        run: pip install --upgrade pip setuptools wheel yapf; sudo apt-get install -y clang-format
      - name: 'Format Check'
        run: ./scripts/format_check.sh
      - name: 'Install Lint tools'
        run: pip install --upgrade pylint
      - name: 'Lint Check'
        run: ./scripts/lint_all.sh
